import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#0f5238',
        'primary-container': '#2d6a4f',
        'primary-fixed': '#b1f0ce',
        'primary-fixed-dim': '#95d4b3',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#0e5138',
        'on-primary-container': '#a8e7c5',
        'secondary': '#3f6653',
        'secondary-container': '#beead1',
        'secondary-fixed': '#c1ecd4',
        'secondary-fixed-dim': '#a5d0b9',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#274e3d',
        'on-secondary-container': '#436b58',
        'tertiary': '#005236',
        'tertiary-container': '#006d48',
        'tertiary-fixed': '#92f7c3',
        'tertiary-fixed-dim': '#75daa8',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005235',
        'on-tertiary-container': '#89edba',
        'background': '#fbf8ff',
        'surface': '#fbf8ff',
        'surface-bright': '#fbf8ff',
        'surface-dim': '#d7d8f4',
        'surface-variant': '#e0e0fc',
        'surface-tint': '#2c694e',
        'surface-container': '#edecff',
        'surface-container-low': '#f4f2ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e6e6ff',
        'surface-container-highest': '#e0e0fc',
        'on-surface': '#181a2e',
        'on-surface-variant': '#404943',
        'on-background': '#181a2e',
        'outline': '#707973',
        'outline-variant': '#bfc9c1',
        'inverse-surface': '#2d2f44',
        'inverse-primary': '#95d4b3',
        'inverse-on-surface': '#f1efff',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'sidebar': '#2b2d42',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      spacing: {
        'gutter': '24px',
        'sidebar-width': '260px',
        'topbar-height': '64px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'stack-xl': '32px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
